
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'Faq': typeof import("../../app/components/Faq.vue").default
  'Gallery': typeof import("../../app/components/Gallery.vue").default
  'Hero': typeof import("../../app/components/Hero.vue").default
  'Testimonials': typeof import("../../app/components/Testimonials.vue").default
  'WhatsApp': typeof import("../../app/components/WhatsApp.vue").default
  'CalculatorSolar': typeof import("../../app/components/calculator/Solar.vue").default
  'NavigationFooter': typeof import("../../app/components/navigation/Footer.vue").default
  'NavigationHeader': typeof import("../../app/components/navigation/Header.vue").default
  'SectionsSectionFour': typeof import("../../app/components/sections/SectionFour.vue").default
  'SectionsSectionOne': typeof import("../../app/components/sections/SectionOne.vue").default
  'SectionsSectionThree': typeof import("../../app/components/sections/SectionThree.vue").default
  'SectionsSectionTwo': typeof import("../../app/components/sections/SectionTwo.vue").default
  'ScriptGoogleMaps': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue").default
  'ScriptGoogleMapsAdvancedMarkerElement': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue").default
  'ScriptGoogleMapsCircle': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue").default
  'ScriptGoogleMapsHeatmapLayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue").default
  'ScriptGoogleMapsInfoWindow': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue").default
  'ScriptGoogleMapsMarker': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue").default
  'ScriptGoogleMapsMarkerClusterer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue").default
  'ScriptGoogleMapsPinElement': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue").default
  'ScriptGoogleMapsPolygon': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue").default
  'ScriptGoogleMapsPolyline': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue").default
  'ScriptGoogleMapsRectangle': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue").default
  'ScriptAriaLoadingIndicator': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue").default
  'ScriptCarbonAds': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue").default
  'ScriptCrisp': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue").default
  'ScriptGoogleAdsense': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue").default
  'ScriptIntercom': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue").default
  'ScriptLemonSqueezy': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue").default
  'ScriptLoadingIndicator': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue").default
  'ScriptPayPalButtons': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue").default
  'ScriptPayPalMarks': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue").default
  'ScriptPayPalMessages': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue").default
  'ScriptStripePricingTable': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue").default
  'ScriptVimeoPlayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue").default
  'ScriptYouTubePlayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue").default
  'UColorModeAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default
  'UColorModeButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default
  'UColorModeImage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default
  'UColorModeSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default
  'UColorModeSwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default
  'UAccordion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default
  'UAlert': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default
  'UApp': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default
  'UAuthForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default
  'UAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default
  'UAvatarGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default
  'UBadge': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default
  'UBanner': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default
  'UBlogPost': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default
  'UBlogPosts': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default
  'UBreadcrumb': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default
  'UButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default
  'UCalendar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default
  'UCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default
  'UCarousel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default
  'UChangelogVersion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default
  'UChangelogVersions': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default
  'UChatMessage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default
  'UChatMessages': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default
  'UChatPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default
  'UChatPrompt': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default
  'UChatPromptSubmit': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default
  'UCheckbox': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default
  'UCheckboxGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default
  'UChip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default
  'UCollapsible': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default
  'UColorPicker': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default
  'UCommandPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default
  'UContainer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default
  'UContextMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default
  'UContextMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default
  'UDashboardGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default
  'UDashboardNavbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default
  'UDashboardPanel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default
  'UDashboardResizeHandle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default
  'UDashboardSearch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default
  'UDashboardSearchButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default
  'UDashboardSidebar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default
  'UDashboardSidebarCollapse': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default
  'UDashboardSidebarToggle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default
  'UDashboardToolbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default
  'UDrawer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default
  'UDropdownMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default
  'UDropdownMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default
  'UEmpty': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default
  'UError': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default
  'UFieldGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default
  'UFileUpload': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default
  'UFooter': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default
  'UFooterColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default
  'UForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default
  'UFormField': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default
  'UHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default
  'UIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default
  'UInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default
  'UInputDate': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default
  'UInputMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default
  'UInputNumber': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default
  'UInputTags': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default
  'UInputTime': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default
  'UKbd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default
  'ULink': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default
  'ULinkBase': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default
  'UMain': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default
  'UMarquee': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default
  'UModal': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default
  'UNavigationMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default
  'UOverlayProvider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default
  'UPage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default
  'UPageAnchors': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default
  'UPageAside': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default
  'UPageBody': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default
  'UPageCTA': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default
  'UPageCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default
  'UPageColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default
  'UPageFeature': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default
  'UPageGrid': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default
  'UPageHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default
  'UPageHero': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default
  'UPageLinks': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default
  'UPageList': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default
  'UPageLogos': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default
  'UPageSection': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default
  'UPagination': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default
  'UPinInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default
  'UPopover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default
  'UPricingPlan': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default
  'UPricingPlans': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default
  'UPricingTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default
  'UProgress': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default
  'URadioGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default
  'USelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default
  'USelectMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default
  'USeparator': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default
  'USkeleton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default
  'USlideover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default
  'USlider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default
  'UStepper': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default
  'USwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default
  'UTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default
  'UTabs': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default
  'UTextarea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default
  'UTimeline': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default
  'UToast': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default
  'UToaster': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default
  'UTooltip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default
  'UTree': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default
  'UUser': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default
  'ULocaleSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index").default
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'OgImage': typeof import("../../node_modules/nuxt-og-image/dist/runtime/app/components/OgImage/OgImage").default
  'OgImageScreenshot': typeof import("../../node_modules/nuxt-og-image/dist/runtime/app/components/OgImage/OgImageScreenshot").default
  'SchemaOrgDebug': typeof import("@unhead/schema-org/vue").SchemaOrgDebug
  'SchemaOrgArticle': typeof import("@unhead/schema-org/vue").SchemaOrgArticle
  'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb
  'SchemaOrgComment': typeof import("@unhead/schema-org/vue").SchemaOrgComment
  'SchemaOrgEvent': typeof import("@unhead/schema-org/vue").SchemaOrgEvent
  'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment
  'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue").SchemaOrgHowTo
  'SchemaOrgImage': typeof import("@unhead/schema-org/vue").SchemaOrgImage
  'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting
  'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness
  'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue").SchemaOrgOrganization
  'SchemaOrgPerson': typeof import("@unhead/schema-org/vue").SchemaOrgPerson
  'SchemaOrgProduct': typeof import("@unhead/schema-org/vue").SchemaOrgProduct
  'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue").SchemaOrgQuestion
  'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue").SchemaOrgRecipe
  'SchemaOrgReview': typeof import("@unhead/schema-org/vue").SchemaOrgReview
  'SchemaOrgVideo': typeof import("@unhead/schema-org/vue").SchemaOrgVideo
  'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue").SchemaOrgWebPage
  'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue").SchemaOrgWebSite
  'SchemaOrgMovie': typeof import("@unhead/schema-org/vue").SchemaOrgMovie
  'SchemaOrgCourse': typeof import("@unhead/schema-org/vue").SchemaOrgCourse
  'SchemaOrgItemList': typeof import("@unhead/schema-org/vue").SchemaOrgItemList
  'SchemaOrgBook': typeof import("@unhead/schema-org/vue").SchemaOrgBook
  'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyFaq': LazyComponent<typeof import("../../app/components/Faq.vue").default>
  'LazyGallery': LazyComponent<typeof import("../../app/components/Gallery.vue").default>
  'LazyHero': LazyComponent<typeof import("../../app/components/Hero.vue").default>
  'LazyTestimonials': LazyComponent<typeof import("../../app/components/Testimonials.vue").default>
  'LazyWhatsApp': LazyComponent<typeof import("../../app/components/WhatsApp.vue").default>
  'LazyCalculatorSolar': LazyComponent<typeof import("../../app/components/calculator/Solar.vue").default>
  'LazyNavigationFooter': LazyComponent<typeof import("../../app/components/navigation/Footer.vue").default>
  'LazyNavigationHeader': LazyComponent<typeof import("../../app/components/navigation/Header.vue").default>
  'LazySectionsSectionFour': LazyComponent<typeof import("../../app/components/sections/SectionFour.vue").default>
  'LazySectionsSectionOne': LazyComponent<typeof import("../../app/components/sections/SectionOne.vue").default>
  'LazySectionsSectionThree': LazyComponent<typeof import("../../app/components/sections/SectionThree.vue").default>
  'LazySectionsSectionTwo': LazyComponent<typeof import("../../app/components/sections/SectionTwo.vue").default>
  'LazyScriptGoogleMaps': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue").default>
  'LazyScriptGoogleMapsAdvancedMarkerElement': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue").default>
  'LazyScriptGoogleMapsCircle': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue").default>
  'LazyScriptGoogleMapsHeatmapLayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue").default>
  'LazyScriptGoogleMapsInfoWindow': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue").default>
  'LazyScriptGoogleMapsMarker': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue").default>
  'LazyScriptGoogleMapsMarkerClusterer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue").default>
  'LazyScriptGoogleMapsPinElement': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue").default>
  'LazyScriptGoogleMapsPolygon': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue").default>
  'LazyScriptGoogleMapsPolyline': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue").default>
  'LazyScriptGoogleMapsRectangle': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue").default>
  'LazyScriptAriaLoadingIndicator': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue").default>
  'LazyScriptCarbonAds': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue").default>
  'LazyScriptCrisp': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue").default>
  'LazyScriptGoogleAdsense': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue").default>
  'LazyScriptIntercom': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue").default>
  'LazyScriptLemonSqueezy': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue").default>
  'LazyScriptLoadingIndicator': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue").default>
  'LazyScriptPayPalButtons': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue").default>
  'LazyScriptPayPalMarks': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue").default>
  'LazyScriptPayPalMessages': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue").default>
  'LazyScriptStripePricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue").default>
  'LazyScriptVimeoPlayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue").default>
  'LazyScriptYouTubePlayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue").default>
  'LazyUColorModeAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default>
  'LazyUColorModeButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default>
  'LazyUColorModeImage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default>
  'LazyUColorModeSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default>
  'LazyUColorModeSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default>
  'LazyUAccordion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default>
  'LazyUAlert': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default>
  'LazyUApp': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default>
  'LazyUAuthForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default>
  'LazyUAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default>
  'LazyUAvatarGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default>
  'LazyUBadge': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default>
  'LazyUBanner': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default>
  'LazyUBlogPost': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default>
  'LazyUBlogPosts': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default>
  'LazyUBreadcrumb': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default>
  'LazyUButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default>
  'LazyUCalendar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default>
  'LazyUCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default>
  'LazyUCarousel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default>
  'LazyUChangelogVersion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default>
  'LazyUChangelogVersions': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default>
  'LazyUChatMessage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default>
  'LazyUChatMessages': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default>
  'LazyUChatPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default>
  'LazyUChatPrompt': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default>
  'LazyUChatPromptSubmit': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default>
  'LazyUCheckbox': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default>
  'LazyUCheckboxGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default>
  'LazyUChip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default>
  'LazyUCollapsible': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default>
  'LazyUColorPicker': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default>
  'LazyUCommandPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default>
  'LazyUContainer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default>
  'LazyUContextMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default>
  'LazyUContextMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default>
  'LazyUDashboardGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default>
  'LazyUDashboardNavbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default>
  'LazyUDashboardPanel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default>
  'LazyUDashboardResizeHandle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default>
  'LazyUDashboardSearch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default>
  'LazyUDashboardSearchButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default>
  'LazyUDashboardSidebar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default>
  'LazyUDashboardSidebarCollapse': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default>
  'LazyUDashboardSidebarToggle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default>
  'LazyUDashboardToolbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default>
  'LazyUDrawer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default>
  'LazyUDropdownMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default>
  'LazyUDropdownMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default>
  'LazyUEmpty': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default>
  'LazyUError': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default>
  'LazyUFieldGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default>
  'LazyUFileUpload': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default>
  'LazyUFooter': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default>
  'LazyUFooterColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default>
  'LazyUForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default>
  'LazyUFormField': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default>
  'LazyUHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default>
  'LazyUIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default>
  'LazyUInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default>
  'LazyUInputDate': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default>
  'LazyUInputMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default>
  'LazyUInputNumber': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default>
  'LazyUInputTags': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default>
  'LazyUInputTime': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default>
  'LazyUKbd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default>
  'LazyULink': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default>
  'LazyULinkBase': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default>
  'LazyUMain': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default>
  'LazyUMarquee': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default>
  'LazyUModal': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default>
  'LazyUNavigationMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default>
  'LazyUOverlayProvider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default>
  'LazyUPage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default>
  'LazyUPageAnchors': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default>
  'LazyUPageAside': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default>
  'LazyUPageBody': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default>
  'LazyUPageCTA': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default>
  'LazyUPageCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default>
  'LazyUPageColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default>
  'LazyUPageFeature': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default>
  'LazyUPageGrid': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default>
  'LazyUPageHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default>
  'LazyUPageHero': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default>
  'LazyUPageLinks': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default>
  'LazyUPageList': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default>
  'LazyUPageLogos': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default>
  'LazyUPageSection': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default>
  'LazyUPagination': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default>
  'LazyUPinInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default>
  'LazyUPopover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default>
  'LazyUPricingPlan': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default>
  'LazyUPricingPlans': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default>
  'LazyUPricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default>
  'LazyUProgress': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default>
  'LazyURadioGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default>
  'LazyUSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default>
  'LazyUSelectMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default>
  'LazyUSeparator': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default>
  'LazyUSkeleton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default>
  'LazyUSlideover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default>
  'LazyUSlider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default>
  'LazyUStepper': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default>
  'LazyUSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default>
  'LazyUTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default>
  'LazyUTabs': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default>
  'LazyUTextarea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default>
  'LazyUTimeline': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default>
  'LazyUToast': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default>
  'LazyUToaster': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default>
  'LazyUTooltip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default>
  'LazyUTree': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default>
  'LazyUUser': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default>
  'LazyULocaleSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index").default>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyOgImage': LazyComponent<typeof import("../../node_modules/nuxt-og-image/dist/runtime/app/components/OgImage/OgImage").default>
  'LazyOgImageScreenshot': LazyComponent<typeof import("../../node_modules/nuxt-og-image/dist/runtime/app/components/OgImage/OgImageScreenshot").default>
  'LazySchemaOrgDebug': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgDebug>
  'LazySchemaOrgArticle': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgArticle>
  'LazySchemaOrgBreadcrumb': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb>
  'LazySchemaOrgComment': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgComment>
  'LazySchemaOrgEvent': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgEvent>
  'LazySchemaOrgFoodEstablishment': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment>
  'LazySchemaOrgHowTo': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgHowTo>
  'LazySchemaOrgImage': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgImage>
  'LazySchemaOrgJobPosting': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting>
  'LazySchemaOrgLocalBusiness': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness>
  'LazySchemaOrgOrganization': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgOrganization>
  'LazySchemaOrgPerson': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgPerson>
  'LazySchemaOrgProduct': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgProduct>
  'LazySchemaOrgQuestion': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgQuestion>
  'LazySchemaOrgRecipe': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgRecipe>
  'LazySchemaOrgReview': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgReview>
  'LazySchemaOrgVideo': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgVideo>
  'LazySchemaOrgWebPage': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebPage>
  'LazySchemaOrgWebSite': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebSite>
  'LazySchemaOrgMovie': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgMovie>
  'LazySchemaOrgCourse': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgCourse>
  'LazySchemaOrgItemList': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgItemList>
  'LazySchemaOrgBook': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBook>
  'LazySchemaOrgSoftwareApp': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
